### ISSUE TITLE
MinMaxBig may set default foundSet?

### ISSUE THREAD

**Issue by ChicChip** [RoaringBitmap/roaring#455] opened 2024-10-29 09:29 UTC
v2.4.0
in "func (b *BSI) MinMaxBig(parallelism int, op Operation, foundSet *Bitmap) *big.Int"
before excute  "card := foundSet.GetCardinality()" need add code
"
if foundSet == nil {
		foundSet = &b.eBM
}
"
then when foundSet is nil , this function will return b.eBM's max or min value?

**Comment by guymolinari** [comment] 2024-10-29 10:52
The purpose of a 'foundSet' is to restrict the operation to a subset of the
contents of a BSI (or other operations such as comparisons).   If a nil
foundSet is passed
then the entire BSI is considered.   If you look at the code you will see
that if a foundSet is not provided, then the existence bitmap is used
instead.  The existence
bitmap of a BSI indicates that a value is present (non NULL) for a given
columnId.

**Comment by guymolinari** [comment] 2024-10-29 10:54
This was a question for clarification and not a bug or feature request so I am closing the issue.

**Comment by ChicChip** [comment] 2024-10-29 10:59
it didn't use existence bitmap in **MinMaxBig** func, and when i use 
`bsi.MinMaxBig(1,roaring64.MAX, nil)`
it will throw a panic
`github.com/RoaringBitmap/roaring/v2/roaring64.(*Bitmap).GetCardinality(0xc000191308?)
        /Users/jidian.shan/Desktop/user-profile-be/vendor/github.com/RoaringBitmap/roaring/v2/roaring64/roaring64.go:390 +0x18
github.com/RoaringBitmap/roaring/v2/roaring64.(*BSI).MinMaxBig(0xc0004d6000, 0x4e1f?, 0x8, 0x152f2e2?)
        /Users/jidian.shan/Desktop/user-profile-be/vendor/github.com/RoaringBitmap/roaring/v2/roaring64/bsi64.go:512 +0x70
`

**Comment by guymolinari** [comment] 2024-10-29 11:39
Yes.   Indeed this should be fixed.  There are a few other places where we should check nil as well.   However, this works per the unit tests.

func TestMinMaxBigWithNegative(t *testing.T) {
    bsi := setupAutoSizeNegativeBoundary()
    assert.Equal(t, big.NewInt(-5), bsi.MinMaxBig(0, MIN, bsi.GetExistenceBitmap())).       //WORKS
    assert.Equal(t, big.NewInt(5), bsi.MinMaxBig(0, MAX, bsi.GetExistenceBitmap()))         //WORKS
    assert.Equal(t, big.NewInt(-5), bsi.MinMaxBig(0, MIN, nil))                                               //BREAKS
    assert.Equal(t, big.NewInt(5), bsi.MinMaxBig(0, MAX, nil))                                               //BREAKS
}

**Comment by guymolinari** [comment] 2024-11-05 16:13
Fixed by ChicChip.

**Closed** 2024-11-05 16:13 UTC
